config/routes.rb
Partymint::Application.routes.draw do

  

  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show do
    resources :posts
  end

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
end

app/models/followers.rb
class Followers < ActiveRecord::Base
end

app/models/following.rb
class Following < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categorizations
  has_many :categories, through: :categorizations

  validates :title, presence: true
  validates :message, presence: true

  has_attached_file :image, :styles => { :small => "150x150>" },
                    :url  => "/assets/images/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"

  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/photos/:id/:style/:basename.:extension",
                    :default_url => "/assets/images/blank_profile.png",
                    :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :photo, :bio, :email, :password, :password_confirmation, :remember_me

  # App logic
  has_many :posts
  has_many :followers
  has_many :followings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @user = User.find(params[:user_id])
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@user,@post], notice: 'Post was successfully created.' }
        format.json { render json: [@user,@post], status: :created, location: [@user,@post] }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to [@user,@post], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all  
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with @user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.email, user %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partymint</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= csrf_meta_tags %>
  <span>
  <%- if user_signed_in? %>
    <%= "Signed in as #{current_user.name}. Not you?" %>
    <%= link_to 'Sign out', destroy_user_session_path %>
  <%- else %>
    <%= link_to 'Sign in', new_user_session_path %>
  <%- end %>
</span>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <div class="field">
    <%= f.label "Title:" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Message:" %><br />
    <%= f.text_area(:message, :size => "44x12") %>
  </div>
  <div class="field">
    <%= f.label "Upload an image:" %><br />
    <%= f.file_field :image, :as => :file, :hint => "Upload an image"%><br />
  <div>

  <div class="actions">
    <br/><%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', user_posts_path(@user) %> |
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.user.name %></td>
    <td><%= post.title %></td>
    <td><%= post.message %></td>
    <td><%= link_to 'Show', [@user, post] %></td>
    <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
    <td><%= link_to 'Destroy', [@user, post], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />


<p><%= link_to "Back to User", @user %></p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<% if @post.image.exists? %>
<p>
  <%= image_tag(@post.image) %>
</p>
<% end %>

<p>
  <h2><%= @post.title %></h2>
</p>

<p>
  <%= @post.message %>
</p>

<% if current_user == @user %>
<%= link_to 'Edit', edit_user_post_path(@user, @post) %> | <%= link_to 'Delete', [@user, @post],confirm: 'Are you sure?', method: :delete,  %> | 
<% end %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @user.photo != nil %>
  <b><%= image_tag @user.photo.url(:small) %></b>
  <% else %>
  <b><%= image_tag("rails.png") %></b>
  <% end %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>

<p><%= link_to "View user's posts", user_posts_path(@user) %></p>

<% if current_user == @user %>
<p><%= link_to "Create a new post", new_user_post_path(@user) %></p>
<% end %>

<% if current_user == @user %>
<%= link_to 'Edit', edit_user_registration_path %> |
<% end %>
<%= link_to 'Back', root_path %>